image: nixos/unstable
sources:
  - https://git.sr.ht/~sumner/sublimemusic.app
environment:
  REPO_NAME: sublimemusic.app
# triggers:
#   - action: email
#     condition: failure
#     to: ~sumner/sublime-music-devel@lists.sr.ht
tasks:
  - setup: |
      echo "cd $REPO_NAME" >> ~/.buildenv

  - build: |
      nix-shell --run make

  - deploy: |
      # Skip if not on master
      git branch --contains | grep master || echo "Skipping deploy since not on master"
      git branch --contains | grep master || complete-build

      # TODO: need to deploy
