image: nixos/nix:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Deploy documenation and code coverage to GitLab Pages
pages:
  only:
    - master
  stage: deploy
  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
  script:
    - nix-shell --run make
  artifacts:
    paths:
      - public
