image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Deploy documenation and code coverage to GitLab Pages
pages:
  only:
    - master
  stage: deploy
  before_script:
    - npm install -g sass uglify-js html-minifier
  script:
    - make
  artifacts:
    paths:
      - public
